src/MovieRecommender/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view, create_account
urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('Movies.urls', namespace='Movies')),
    path('profile/', include('Profile.urls', namespace="Profile")),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='login'),
    path('create_user/', create_account, name='create-account')
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

src/Movies/urls.py
from django.urls import path 
import asyncio
from .views import (
    home_view,
    detail_view,
    show_graphs,
    index,
    homepage,
    add_watchlist,
)

app_name = 'movies'

urlpatterns = [
    path('',homepage,name="home"),
    path('stats',show_graphs,name='graph'),
    path('movies',home_view, name='movies'),
    path('movies/<pk>',detail_view, name='detail'),
    path('search',index, name='search-movies'),
    path('description', add_watchlist, name="description"),
]

src/Profile/urls.py
from django.urls import path
from .views import my_profile_view, watchlist, personal_stats

app_name = 'profiles'

urlpatterns = [
    path('my_profile', my_profile_view, name="profile"),
    path('watchlist', watchlist, name="watchlist"),
    path('personal_stats', personal_stats, name="pers_stats")
]

src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Requrired Meta Data -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- favicon -->
<!--    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
          crossorigin="anonymous">
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>
    <!-- Dropzone js -->
<!--    <link rel="stylesheet" href="{% static 'dropzone.css' %}">-->
<!--    <script src="{% static 'dropzone.js' %}" defer></script>-->

    <!-- Custom js & css -->

    <script src="{% static "loading.js"%}"></script>
    <link rel="stylesheet" href="{% static "style.css" %}">
    <link rel="stylesheet" href="{% static "Movies/style.css" %}">
    {% block scripts %}
    {% endblock scripts %}

    <title>Movie Recommender | {% block title %}{% endblock title %}</title>
  </head>
  <body onload="loading()">
    <div id="loader"></div>
    {% include 'navbar.html' %}
    <div class="main-container container mt-5 mb-3 align-item-center justify-content-center" id="myDiv" style="display:none;">
        {% block content %}
        {% endblock content %}

    </div>
    <!-- Bootstrap js -->
     <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
  </body>

  


</html>

src/templates/navbar.html
{% load static %}
    <nav class="navbar navbar-expand-lg border-bottom border-body nav-banner" data-bs-theme="dark" id="myNavDiv" style="display:none">
    <div class="container-fluid">
      <a class="navbar-brand" href="#"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" style="color: #E4F1F6" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "Movies:movies" %}">Movies</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "Profile:watchlist"%}">Watch List</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              More
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url "Movies:graph" %}">Global Stats</a></li>
              <li><a class="dropdown-item" href="{% url "Profile:pers_stats"%}">Your Stats</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url "Movies:description"%}">About this project</a></li>
            </ul>
          </li>
          
        </ul>
        <form class="form-inline my-2 my-lg-0 ml-auto" method=GET action="{% url 'Movies:search-movies' %}">
          {% csrf_token %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item"><input class="form-control mr-sm-2 search-input" type="search" placeholder="Search Movies" name="title" aria-label="Search"></li> &nbsp;&nbsp;
          <li class="nav-item"><button class="custombutton" type="submit"><i class="fa fa-search" aria-hidden="true"></i></button></li>
        </ul>
          {% comment %} <button class="btn btn-outline-danger my-2 my-sm-0"><i class="fa fa-search p pr-5" aria-hidden="true"></i></button> {% endcomment %}
        </form>
        <ul class="navbar-nav ml-auto">
          {% if request.user.is_authenticated %}
          <li class="nav-item dropdown" style='color: white;'>
              <div class="nav-link dropdown-toggle" id="navbarDropDownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <img src="" class="">&nbsp;{{request.user}}{%if request.user.is_superuser %} (admin) {%endif%}
              </div>
              <ul class="dropdown-menu" aria-labelledby="navbarDropDownMenuLink">
  <li><a class="dropdown-item" href="{% url "Profile:profile"%}">Profile</a></li>
                <li><a class="dropdown-item" href="/logout">Logout</a></li>
              </ul>
            </div>
          {% else %}
          <a class="nav-item initial-btn" aria-current="page" href="/login">&nbsp;&nbsp;Login</a>
          <a class="nav-item initial-btn" aria-current="page" href="/create_user">&nbsp;&nbsp;Create</a>
            {% endif %}
          </ul>
      </div>
    </div>
  </nav>
  

{% comment %} 
<nav class="navbar bg-body-tertiary fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Offcanvas navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Offcanvas</h5>
          <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li>
                  <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>
          <form class="d-flex mt-3" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </div>
  </nav> {% endcomment %}

src/templates/temp.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Requrired Meta Data -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- favicon -->
<!--    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
          crossorigin="anonymous">
    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>
    <!-- Dropzone js -->
<!--    <link rel="stylesheet" href="{% static 'dropzone.css' %}">-->
<!--    <script src="{% static 'dropzone.js' %}" defer></script>-->

    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static "style.css" %}">
    <link rel="stylesheet" href="{% static "Movies/style.css" %}">
    {% block scripts %}
    {% endblock scripts %}

    <title>Movie Recommender | {% block title %}{% endblock title %}</title>
  </head>
  <body>

    {% comment %} {% include 'navbar.html' %} {% endcomment %}
    <div class="main-container  container mt-5 mb-3 align-item-center justify-content-center">
        {% block content %}
        {% endblock content %}

    </div>
    <!-- Bootstrap js -->
     <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
  </body>

  


</html>